export const JOURNAL_CONFIG = {
    // Timing
    AUTOSAVE_DEBOUNCE_MS: 15000,
    SIGNED_URL_EXPIRY_SECONDS: 604800, // 7 days
    VISIBILITY_REFRESH_DEBOUNCE_MS: 10000,
    OCR_TIMEOUT_MS: 20000,
    AUDIO_DELETE_DELAY_MS: 2500,

    // Recording limits (HARD ENFORCED - auto-stop on limit)
    MAX_RECORDING_DURATION_SECONDS: 600, // 10 minutes max for audio/video

    // Size limits
    MAX_RAW_IMAGE_SIZE_MB: 50,
    MAX_COMPRESSED_IMAGE_SIZE_MB: 10,
    MAX_OCR_IMAGE_SIZE_MB: 4,

    // Image compression
    IMAGE_UPLOAD_QUALITY: 0.85,
    IMAGE_UPLOAD_MAX_SIZE: 2048,
    OCR_IMAGE_QUALITY: 0.8,
    OCR_IMAGE_MAX_SIZE: 1024,

    // Cache
    CACHE_CLEANUP_PERCENTAGE: 0.2,
    MIN_CACHE_ENTRIES_TO_REMOVE: 5,
} as const;
